#!/bin/bash

#
# Global Variables
#
BASENAME=$0

#
# Check effective UID
#
MYUID=`id -u`
if [ "${MYUID}" -ne 0 ]; then

  echo ""
  echo "Must be run as root"
  echo ""

fi

#
# Get info we need
#
if [ "$#" -ne 1 ]; then

  echo ""
  echo "Usage:"
  echo "  ${BASENAME} GUID"
  echo "  e.g. ${BASENAME} SESW"
  echo ""
  exit 1

fi

GUID=${1}

echo ""
echo "Building OCP inventory for ${GUID}"
echo ""
ansible-playbook -i /etc/ansible/hosts -e "osrelease=3.9" -e "ANSIBLE_REPO_PATH=`pwd`" -e "guid=${GUID}" -e "internaldns=internal" config/setup_hosts.yml


#echo ""
#echo "Building OCP cluster on ${GUID}"
#echo ""
#
#ansible-playbook -i 127.0.0.1, ansible/main.yml -e "env_type=config-name" -e "aws_region=ap-southeast-2" -e "guid=${GUID}"
#


