# #

cicd_project: 'cicd'
company_projs:
  - proj: alpha-dev
    display: "Alpha Corp - Dev"
    admins:
      - admin: amy
      - admin: andrew
      - admin: steve
  - proj: alpha-stage
    display: "Alpha Corp - Stage"
    admins:
      - admin: amy
      - admin: andrew
      - admin: steve
  - proj: beta-dev
    display: "Beta Corp - Dev"
    admins:
      - admin: brian
      - admin: betty
      - admin: steve
  - proj: beta-stage
    display: "Beta Corp - Stage"
    admins:
      - admin: brian
      - admin: betty
      - admin: steve
  - proj: common-dev
    display: "Common - Dev"
    admins:
      - admin: steve
  - proj: common-stage
    display: "Common - Stage"
    admins:
      - admin: steve
company_users:
  amy:
  andrew:
  brian:
  betty:
  steve:

