# vim: set ft=ansible:

cicd_project: 'cicd'
company_projs:
  - proj: cicd
    display: "CI/CD"
    users:
      - steve
    client: build
  - proj: alpha-dev
    display: "Alpha Corp - Dev"
    users:
      - amy
      - andrew
    client: alpha
  - proj: alpha-stage
    display: "Alpha Corp - Stage"
    users:
      - amy
      - andrew
    client: alpha
  - proj: beta-dev
    display: "Beta Corp - Dev"
    users:
      - brian
      - betty
    client: beta
  - proj: beta-stage
    display: "Beta Corp - Stage"
    users:
      - brian
      - betty
    client: beta
  - proj: cicd-dev
    display: "CICD - Dev"
    users:
      - steve
    client: common
  - proj: cicd-test
    display: "CICD - Stage"
    users:
      - steve
    client: common
  - proj: cicd-prod
    display: "CICD - Prod"
    users:
      - steve
    client: common
company_users:
  amy:
  andrew:
  brian:
  betty:
  steve:
  steve-admin:
cadmins_users:
  steve-admin:
  cadmin1:

