# #

cicd_project: 'cicd'
company_projs:
  - proj: cicd
    display: "CI/CD"
    admins:
      - admin: steve
    client: build
  - proj: alpha-dev
    display: "Alpha Corp - Dev"
    admins:
      - admin: amy
      - admin: andrew
      - admin: steve
    client: alpha
  - proj: alpha-stage
    display: "Alpha Corp - Stage"
    admins:
      - admin: amy
      - admin: andrew
      - admin: steve
    client: alpha
  - proj: beta-dev
    display: "Beta Corp - Dev"
    admins:
      - admin: brian
      - admin: betty
      - admin: steve
    client: beta
  - proj: beta-stage
    display: "Beta Corp - Stage"
    admins:
      - admin: brian
      - admin: betty
      - admin: steve
    client: beta
  - proj: common-dev
    display: "Common - Dev"
    admins:
      - admin: steve
    client: common
  - proj: common-stage
    display: "Common - Stage"
    admins:
      - admin: steve
    client: common
  - proj: common-prod
    display: "Common - Prod"
    admins:
      - admin: steve
    client: common
company_users:
  amy:
  andrew:
  brian:
  betty:
  steve:
  steve-admin:
cadmins_users:
  steve-admin:

