# vim: set ft=ansible:

cicd_project: 'cicd-dev'
infra_projs:
  - proj: cicd-dev
    display: "CI/CD"
    users:
      - steve
    client: build
company_projs:
  - proj: alpha-dev
    display: "Alpha Corp - Dev"
    users:
      - amy
      - andrew
    client: alpha
  - proj: alpha-stage
    display: "Alpha Corp - Stage"
    users:
      - amy
      - andrew
    client: alpha
  - proj: beta-dev
    display: "Beta Corp - Dev"
    users:
      - brian
      - betty
    client: beta
  - proj: beta-stage
    display: "Beta Corp - Stage"
    users:
      - brian
      - betty
    client: beta
  - proj: tasks-build
    display: "Tasks - Build"
    users:
      - steve
    client: common
  - proj: tasks-dev
    display: "Tasks - Dev"
    users:
      - steve
    client: common
  - proj: tasks-test
    display: "Tasks - Stage"
    users:
      - steve
    client: common
  - proj: tasks-prod
    display: "Tasks - Prod"
    users:
      - steve
    client: common
company_users:
  amy:
  andrew:
  brian:
  betty:
  steve:
  steve-admin:
cadmins_users:
  steve-admin:
  cadmin1:

