---

- name: Setup storage
  hosts: nfs
  gather_facts: False
  become: yes
  vars_files:
    - "{{ ANSIBLE_REPO_PATH }}/config/env_vars.yml"
  tags:
    - setup_storage
  tasks:
    - name: Create vols
      shell: "mkdir -p /srv/nfs/user-vols/vol{1..{{user_vols}}}"
    - name: Change perms
      shell: "chmod -R 777 /srv/nfs/user-vols"

- name: Create PVs
  hosts: localhost
  gather_facts: False
  become: yes
  vars_files:
    - "{{ ANSIBLE_REPO_PATH }}/config/env_vars.yml"
  tasks:
    - name: get nfs Hostname
      set_fact:
        nfs_host: "{{ groups['nfs']|sort|first }}"

    - set_fact:
        pv_size: '10Gi'
        pv_list: "{{ ocp_pvs }}"
        persistentVolumeReclaimPolicy: Retain

    - name: Generate PV file
      template:
        src: "{{ ANSIBLE_REPO_PATH }}/config/pvs.j2"
        dest: "/root/pvs-{{ guid }}.yml"
      tags: [ gen_pv_file ]
      when: pv_list.0 is defined

    - set_fact:
        pv_size: "{{user_vols_size}}"
        persistentVolumeReclaimPolicy: Recycle

      notify: restart nfs services
      run_once: True

    - name: Generate user vol PV file
      template:
        src: "{{ ANSIBLE_REPO_PATH }}/config/userpvs.j2"
        dest: "/root/userpvs-{{ guid }}.yml"
      tags:
        - gen_user_vol_pv


    - shell: 'oc create -f /root/pvs-{{ guid }}.yml || oc replace -f /root/pvs-{{ guid }}.yml'
      tags:
        - create_user_pv
      when: pv_list.0 is defined

    - shell: 'oc create -f /root/userpvs-{{ guid }}.yml || oc replace -f /root/userpvs-{{ guid }}.yml'
      tags:
        - create_user_pv

