---

- name: Create projects
  hosts: localhost
  gather_facts: False
  become: yes
  vars_files:
    - "{{ ANSIBLE_REPO_PATH }}/config/clients_env_var.yml"
  tasks:
    - name: Unique list of clients
      shell: "oc get nodes -lenv=app -o custom-columns=NAME:.metadata.name --sort-by=.metadata.name --no-headers=true 2>/dev/null"
      register: app_node_list
#      ignore_errors: yes
#      failed_when: false
#      changed_when: false

    - name: Restrict nodes
      shell: "{{ ANSIBLE_REPO_PATH }}/scripts/restrict_node {{ item.0 }} {{ item.1 }}"
      when: item.0 != ""
      with_together:
        - "{{ company_projs | map(attribute='client') | list | unique }}"
        - "{{ app_node_list.stdout_lines }}"

#    - name: Combine lists
#      set_fact: 
#        client: "{{ item.0 }}"
#        nodename: {{ item.1 }}
#      debug: msg="A{{ item.0 }}B and {{ item.1 }}"
#      when: item.1 != ""
#        - item.1 != ""
#      with_together:
#        - "{{ company_projs | map(attribute='client') | list | unique }}"
#        - "{{ app_node_list.stdout_lines }}"

